Repository TikiTaka-TeamProject/BapZip, pull requests merged in 2025-10, with the labels that each got.

#21 feat: menu 엔티티 추가 및 수정
  src/main/java/com/sparta/bapzip/menu/domain/entity/MenuEntity.java
  src/main/java/com/sparta/bapzip/menu/domain/enums/MenuStatus.java
  src/main/java/com/sparta/bapzip/menu/domain/repository/MenuRepository.java
  src/main/java/com/sparta/bapzip/menu/infrastructure/repository/MenuJpaRepository.java
  src/main/java/com/sparta/bapzip/menu/infrastructure/repository/MenuRepositoryImpl.java
  src/main/java/com/sparta/bapzip/menu/presentation/controller/MenuControllerV1.java
Labels: fix, add

#27 feat: 메뉴 상세 조회 API 구현
  src/main/java/com/sparta/bapzip/global/exception/ErrorCode.java
  src/main/java/com/sparta/bapzip/menu/application/MenuServiceV1.java
  src/main/java/com/sparta/bapzip/menu/domain/repository/MenuRepository.java
  src/main/java/com/sparta/bapzip/menu/infrastructure/repository/MenuJpaRepository.java
  src/main/java/com/sparta/bapzip/menu/infrastructure/repository/MenuRepositoryImpl.java
  src/main/java/com/sparta/bapzip/menu/presentation/controller/MenuControllerV1.java
  src/main/java/com/sparta/bapzip/menu/presentation/dto/response/MenuDetailResponse.java
  src/main/java/com/sparta/bapzip/menu/presentation/dto/response/ResponseDto.java
Labels: feat

#32 Feat: 회원가입 API 구현
  src/main/java/com/sparta/bapzip/global/common/BaseEntity.java
  src/main/java/com/sparta/bapzip/global/exception/ErrorCode.java
  src/main/java/com/sparta/bapzip/global/infrastructure/config/security/SecurityConfig.java
  src/main/java/com/sparta/bapzip/user/application/UserServiceV1.java
  src/main/java/com/sparta/bapzip/user/application/excpetion/DuplicateUserException.java
  src/main/java/com/sparta/bapzip/user/application/excpetion/UnauthorizedUserException.java
  src/main/java/com/sparta/bapzip/user/domain/entity/UserEntity.java
  src/main/java/com/sparta/bapzip/user/domain/enums/UserRoleEnum.java
  src/main/java/com/sparta/bapzip/user/domain/repository/UserRepository.java
  src/main/java/com/sparta/bapzip/user/infrastructure/repository/UserJpaRepository.java
  src/main/java/com/sparta/bapzip/user/infrastructure/repository/UserRepositoryImpl.java
  src/main/java/com/sparta/bapzip/user/presentation/controller/UserControllerV1.java
  src/main/java/com/sparta/bapzip/user/presentation/dto/request/RequestDto.java
  src/main/java/com/sparta/bapzip/user/presentation/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/bapzip/user/presentation/dto/response/ResponseDto.java
  src/main/java/com/sparta/bapzip/user/presentation/dto/response/SignupResponseDto.java
Labels: feat

#25 feat: 결제 승인요청 / 결제 취소 요청 구현
  build.gradle
  src/main/java/com/sparta/bapzip/BapzipApplication.java
  src/main/java/com/sparta/bapzip/global/common/BaseEntity.java
  src/main/java/com/sparta/bapzip/global/exception/ErrorCode.java
  src/main/java/com/sparta/bapzip/order/domain/entity/OrderEntity.java
  src/main/java/com/sparta/bapzip/order/domain/repository/OrderRepository.java
  src/main/java/com/sparta/bapzip/order/infrastructure/repository/OrderJpaRepository.java
  src/main/java/com/sparta/bapzip/order/infrastructure/repository/OrderRepositoryImpl.java
  src/main/java/com/sparta/bapzip/payment/application/PaymentServiceV1.java
  src/main/java/com/sparta/bapzip/payment/domain/entity/PaymentEntity.java
  src/main/java/com/sparta/bapzip/payment/domain/entity/PaymentStatusEnum.java
  src/main/java/com/sparta/bapzip/payment/domain/repository/PaymentRepository.java
  src/main/java/com/sparta/bapzip/payment/infrastructure/config/payment/TossPaymentsConfig.java
  src/main/java/com/sparta/bapzip/payment/infrastructure/repository/PaymentJpaRepository.java
  src/main/java/com/sparta/bapzip/payment/infrastructure/repository/PaymentRepositoryImpl.java
  src/main/java/com/sparta/bapzip/payment/presentation/controller/PaymentControllerV1.java
  src/main/java/com/sparta/bapzip/payment/presentation/dto/request/PaymentCancelRequest.java
  src/main/java/com/sparta/bapzip/payment/presentation/dto/request/PaymentCreateRequest.java
  src/main/java/com/sparta/bapzip/payment/presentation/dto/request/RequestDto.java
  src/main/java/com/sparta/bapzip/payment/presentation/dto/response/PaymentResponseDto.java
  src/main/java/com/sparta/bapzip/payment/presentation/dto/response/ResponseDto.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat, add

#33 Feat: JWT를 활용한 로그인 API 구현
  build.gradle
  src/main/java/com/sparta/bapzip/global/exception/ErrorCode.java
  src/main/java/com/sparta/bapzip/global/infrastructure/config/security/SecurityConfig.java
  src/main/java/com/sparta/bapzip/user/application/UserDetailsServiceImpl.java
  src/main/java/com/sparta/bapzip/user/application/excpetion/UserNotFoundException.java
  src/main/java/com/sparta/bapzip/user/domain/entity/UserDetailsImpl.java
  src/main/java/com/sparta/bapzip/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/bapzip/user/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/bapzip/user/jwt/JwtUtil.java
  src/main/java/com/sparta/bapzip/user/presentation/dto/request/LoginRequestDto.java
  src/main/resources/application.yml
Labels: feat

#35 feat: 메뉴 생성 API 구현
  src/main/java/com/sparta/bapzip/menu/application/MenuServiceV1.java
  src/main/java/com/sparta/bapzip/menu/domain/entity/MenuEntity.java
  src/main/java/com/sparta/bapzip/menu/infrastructure/repository/MenuRepositoryImpl.java
  src/main/java/com/sparta/bapzip/menu/presentation/controller/MenuControllerV1.java
  src/main/java/com/sparta/bapzip/menu/presentation/dto/request/MenuCreateRequest.java
  src/main/java/com/sparta/bapzip/menu/presentation/dto/request/RequestDto.java
  src/main/java/com/sparta/bapzip/menu/presentation/dto/response/MenuCreateResponse.java
Labels: feat, refactor

#36 feat: Owner 가게 정보 수정 및 권한 검증 기능 구현
  README.MD
  src/main/java/com/sparta/bapzip/category/application/CategoryServiceV1.java
  src/main/java/com/sparta/bapzip/category/domain/entity/CategoryEntity.java
  src/main/java/com/sparta/bapzip/category/domain/repository/CategoryRepository.java
  src/main/java/com/sparta/bapzip/category/infrastructure/repository/CategoryRepositoryImpl.java
  src/main/java/com/sparta/bapzip/global/exception/ErrorCode.java
  src/main/java/com/sparta/bapzip/servicearea/application/ServiceAreaServiceV1.java
  src/main/java/com/sparta/bapzip/servicearea/domain/repository/ServiceAreaRepository.java
  src/main/java/com/sparta/bapzip/servicearea/infrastructure/repository/ServiceAreaJpaRepository.java
  src/main/java/com/sparta/bapzip/servicearea/infrastructure/repository/ServiceAreaRepositoryImpl.java
  src/main/java/com/sparta/bapzip/shop/application/ShopServiceV1.java
  src/main/java/com/sparta/bapzip/shop/domain/entity/ShopEntity.java
  src/main/java/com/sparta/bapzip/shop/domain/entity/ShopStatusEnum.java
  src/main/java/com/sparta/bapzip/shop/presentation/controller/ShopControllerV1.java
  src/main/java/com/sparta/bapzip/shop/presentation/dto/request/ShopUpdateRequest.java
  src/test/java/com/sparta/bapzip/shop/application/ShopServiceV1Test.java
Labels: feat, docs
